Adds the Modal component
forumone/nextjs-project pull request #135
Opened 2024-07-10 14:12 UTC by SirJohn96

2024-07-10 18:26 UTC, kmonahan requested changes
Thanks @SirJohn96 ! Let me know if you've got any questions about my comments here.

2024-07-10 18:26 UTC, kmonahan commented on source/03-components/Modal/Modal.tsx
> +  });
Missing the dependency array here

2024-07-10 18:26 UTC, kmonahan commented on source/03-components/Modal/Modal.tsx
> +  id,
Let's make this optional and set it with `useId()` if one isn't provided

2024-07-10 18:26 UTC, kmonahan commented on source/03-components/Modal/Modal.tsx
> +  });
Also missing a cleanup function. The event listeners you add need to be removed if the component is unmounted.

I'm wondering if there's a cleaner, more React-y way to handle the open modal functionality, since this won't catch buttons that are added after the dialog component is created. I'm going to ponder that; I think it can be a follow-up PR if needed.

2024-07-10 18:26 UTC, kmonahan commented on source/03-components/Modal/Modal.tsx
> +    if (target && target.closest && target.closest(`dialog > div`)) return;
I'd prefer not to rely on a specific HTML structure here. You're trying to see if the click comes from anywhere other than inside the modal, so you can return without closing it, correct? I think you want to do something more like the original, where you reference the inner class (which is `styles.inner` here), or use a ref.

2024-07-10 18:26 UTC, kmonahan commented on source/03-components/Modal/Modal.tsx
> +    modal.addEventListener('keydown', e => {
Since you're adding the event listener to the modal here, not globally to the window or document, you should be able to use `onKeydown` instead of the manual key binding.

2024-07-10 18:26 UTC, kmonahan commented on source/03-components/Modal/Modal.tsx
> +        ></button>
Needs `type="button"` here. Usually the linter catches that, but we may not have that set up for nextjs-project yet.

2024-07-10 18:26 UTC, kmonahan commented on source/03-components/Modal/modal.module.css
> +      background-color: rgba(0 0 0 / 75%);
While `rgba()` may work, since right now browsers are treating it as an alias, this should be `rgb()`. (Everything else stays the same -- just delete the 'a' and you're good!)

2024-07-10 18:26 UTC, kmonahan commented on source/03-components/Modal/Modal.tsx
> +import clsx from 'clsx';
This will need to be a client component since it includes client-side JS, so please include `'use client'` at the very top.

2024-07-10 21:44 UTC, SirJohn96 commented on source/03-components/Modal/Modal.tsx
> +  });
This has been addressed.

2024-07-10 21:44 UTC, SirJohn96 commented on source/03-components/Modal/Modal.tsx
> +  id,
This has been addressed.

2024-07-10 21:44 UTC, SirJohn96 commented on source/03-components/Modal/Modal.tsx
> +    if (target && target.closest && target.closest(`dialog > div`)) return;
This has been addressed.

2024-07-10 21:44 UTC, SirJohn96 commented on source/03-components/Modal/Modal.tsx
> +    modal.addEventListener('keydown', e => {
This has been addressed.

2024-07-10 21:44 UTC, SirJohn96 commented on source/03-components/Modal/Modal.tsx
> +        ></button>
This has been addressed.

2024-07-10 21:45 UTC, SirJohn96 commented on source/03-components/Modal/modal.module.css
> +      background-color: rgba(0 0 0 / 75%);
This has been addressed.

2024-07-10 21:45 UTC, SirJohn96 commented on source/03-components/Modal/Modal.tsx
> +import clsx from 'clsx';
This has been addressed.

2024-08-19 15:00 UTC, kmonahan approved these changes

2024-08-19 15:00 UTC, merged